apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibmmqs-cwd-pvc
  namespace: middleware
spec:
  accessModes:
    - ReadWriteMany
  # storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
