apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibmmqs-log-pvc
  namespace: middleware
spec:
  accessModes:
    - ReadWriteMany
  # storageClassName: 
  resources:
    requests:
      storage: 1Gi
