apiVersion: v1
kind: Service
metadata:
  name: ibmmqs
  namespace: middleware
  labels:
    app: ibmmqs
spec:
  type: NodePort
  selector:
    app: ibmmqs
  ports:
    - name: mq-channel
      port: 1414
      targetPort: 1414
      nodePort: 31144
    - name: mq-web
      port: 9443
      targetPort: 9443
      nodePort: 31443
    - name: mq-metrics
      port: 9157
      targetPort: 9157
      nodePort: 31157
