apiVersion: v1
kind: Service
metadata:
  name: ibmmq
  namespace: middleware
  labels:
    app: ibmmq-dev
spec:
  type: NodePort
  selector:
    app: ibmmq-dev
  ports:
    - name: mq-channel
      port: 1414
      targetPort: 1414
      nodePort: 30144
    - name: mq-web
      port: 9443
      targetPort: 9443
      nodePort: 30443
    - name: mq-metrics
      port: 9157
      targetPort: 9157
      nodePort: 30157
